import Head from 'next/head'
import styles from '../styles/home.module.css'
import fetch from 'isomorphic-unfetch';
import Header from '../components/header'
import Link from 'next/link';
import Footer from '../components/footer';

export default function Home({contacts}) {
  return (
    <>
      <Head>
        <title>gestion contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <Header/>
      <h1 style={{fontWeight:"700", marginLeft:"20%"}}>Contacts</h1>
      
      <main className={styles.container}>
        <table>

          <thead className={styles.table_row_head}>
            <tr>
                    <th className={styles.table_dh}>Nom</th>
                    <th className={styles.table_dh}>Prenom</th>
                    <th className={styles.table_dh}>Numero</th>
                    <th className={styles.table_dh}>Adresse mail</th>
            </tr>
          </thead>

          <tbody className={styles.table_row_body}>
            {contacts.map(contact =>{
                return(
                  <tr >
                      <td className={styles.table_dh}>
                        <Link href={`/${contact._id}`}>
                          <a>
                            {contact.nom}
                          </a>
                        </Link>
                      </td>

                      <td className={styles.table_dh}>
                        <Link href={`/${contact._id}`}>
                            <a>
                              {contact.prenom}
                            </a>
                        </Link>
                      </td>

                      <td className={styles.table_dh}>
                          <Link href={`/${contact._id}`}>
                            <a>
                              {contact.phone}
                            </a>
                          </Link>
                        </td>

                      <td className={styles.table_dh}>
                        <Link href={`/${contact._id}`}>
                          <a>
                            {contact.email}
                          </a>
                        </Link>
                      </td>
                  </tr>
                )
              })}
          </tbody>
        </table>
      </main>
      <Footer/>
    </>
  )
}

Home.getInitialProps = async () => {
  const res = await fetch('http://localhost:3000/api/contacts')
  const { data } = await res.json();

  return { contacts: data }
}

