import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link';
import fetch from 'isomorphic-unfetch';
import Header from '../components/header'

export default function Home({contacts}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <main >
        <table>
          <thead>
            <tr>
              <th>Nom</th>
              <th>Prenom</th>
              <th>Numero</th>
              <th>Adresse mail</th>
            </tr>
          </thead>
          <tbody>
          {contacts.map(contact =>{
            return(
              <Link href={`/${contact._id}`}>
                <a>
                  <tr>
                    <td>{contact.nom}</td>
                    <td>{contact.prenom}</td>
                    <td>{contact.numero}</td>
                    <td>{contact.email}</td>
                  </tr>
                </a>
              </Link>
            )
          })}
          </tbody>
        </table>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}

Home.getInitialProps = async () => {
  const res = await fetch('http://localhost:3000/api/contacts')
  const { data } = await res.json();

  return { contacts: data }
}